//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutionsWebServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuscont
    {
        public string Ccccuscont { get; set; }
        public string Ccccusmast { get; set; }
        public string Ccccontcde { get; set; }
        public string Ccccatcde { get; set; }
        public string Ccccontact { get; set; }
        public string Ccccontmsc { get; set; }
        public string Cccphone1 { get; set; }
        public string Cccphone2 { get; set; }
        public string Cccphone3 { get; set; }
        public string Cccemail { get; set; }
        public string Cccsalcde { get; set; }
        public string Cccfname { get; set; }
        public string Cccmname { get; set; }
        public string Ccclname { get; set; }
        public string Cccemlbody { get; set; }
        public string Ccmnotes { get; set; }
    
        public virtual Cusmast Cusmast { get; set; }
    }
}
