//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalStaffingSolutionsWebServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cusmast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cusmast()
        {
            this.Cusconts = new HashSet<Cuscont>();
        }
    
        public string Cuccusmast { get; set; }
        public string Cuccustid { get; set; }
        public string Cucrecmast { get; set; }
        public string Cucsitecde { get; set; }
        public string Cucname { get; set; }
        public string Cucaddr1 { get; set; }
        public string Cucaddr2 { get; set; }
        public string Cuccity { get; set; }
        public string Cucstate { get; set; }
        public string Cuczipcode { get; set; }
        public string Cuccountry { get; set; }
        public string Cucstatus { get; set; }
        public string Cucoffcde { get; set; }
        public string Cucsm1cde { get; set; }
        public string Cucsm2cde { get; set; }
        public string Cucloccde { get; set; }
        public string Cucbuscde { get; set; }
        public Nullable<System.DateTime> Cutadded { get; set; }
        public string Cucblable { get; set; }
        public string Cucstaxcde { get; set; }
        public string Cucschgcde { get; set; }
        public string Cucsttxcde { get; set; }
        public string Cuccttxcde { get; set; }
        public string Cucdeunion { get; set; }
        public string Cucwglnk1 { get; set; }
        public string Cucpono { get; set; }
        public string Cucrelno { get; set; }
        public string Cucprojno { get; set; }
        public string Cucgenexp { get; set; }
        public string Cucschrecd { get; set; }
        public string Cucdstadj { get; set; }
        public string Cucoldkey { get; set; }
        public System.DateTime Cutlastexp { get; set; }
        public System.DateTime Cutlastimp { get; set; }
        public string Cucimpexp { get; set; }
        public string Cucmergeid { get; set; }
        public string Cucbrnchid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuscont> Cusconts { get; set; }
    }
}
